# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run the gemspec command
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{rtunnel}
  s.version = "0.0.0"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["coderrr"]
  s.date = %q{2010-08-29}
  s.description = %q{More robust than ssh's reverse tunnel mechanism.'}
  s.email = %q{coderrr.contact@gmail.com}
  s.executables = ["rtunnel_client", "rtunnel_server"]
  s.extra_rdoc_files = [
    "LICENSE",
     "README.markdown"
  ]
  s.files = [
    ".gitignore",
     "CHANGELOG",
     "LICENSE",
     "Manifest",
     "README.markdown",
     "Rakefile",
     "VERSION",
     "bin/rtunnel_client",
     "bin/rtunnel_server",
     "lib/rtunnel.rb",
     "lib/rtunnel/client.rb",
     "lib/rtunnel/command_processor.rb",
     "lib/rtunnel/command_protocol.rb",
     "lib/rtunnel/commands.rb",
     "lib/rtunnel/connection_id.rb",
     "lib/rtunnel/core.rb",
     "lib/rtunnel/crypto.rb",
     "lib/rtunnel/frame_protocol.rb",
     "lib/rtunnel/io_extensions.rb",
     "lib/rtunnel/leak.rb",
     "lib/rtunnel/rtunnel_client_cmd.rb",
     "lib/rtunnel/rtunnel_server_cmd.rb",
     "lib/rtunnel/server.rb",
     "lib/rtunnel/socket_factory.rb",
     "rtunnel.gemspec",
     "test/client_test.rb",
     "test/command_protocol_test.rb",
     "test/commands_test.rb",
     "test/connection_id_test.rb",
     "test/crypto_test.rb",
     "test/frame_protocol_test.rb",
     "test/helpers/command_stubs.rb",
     "test/helpers/protocol_mocks.rb",
     "test/helpers/scenario_connection.rb",
     "test/io_extensions_test.rb",
     "test/server_test.rb",
     "test/socket_factory_test.rb",
     "test/test_helper.rb",
     "test/tunnel_test.rb",
     "test_data/authorized_keys2",
     "test_data/known_hosts",
     "test_data/random_rsa_key",
     "test_data/ssh_host_dsa_key",
     "test_data/ssh_host_rsa_key",
     "tests/_ab_test.rb",
     "tests/_stress_test.rb",
     "tests/lo_http_server.rb"
  ]
  s.homepage = %q{http://github.com/coderrr/rtunnel}
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.rubyforge_project = %q{rtunnel}
  s.rubygems_version = %q{1.3.7}
  s.summary = %q{Reverse tunnel server and client.}
  s.test_files = [
    "test/client_test.rb",
     "test/command_protocol_test.rb",
     "test/commands_test.rb",
     "test/connection_id_test.rb",
     "test/crypto_test.rb",
     "test/frame_protocol_test.rb",
     "test/helpers/command_stubs.rb",
     "test/helpers/protocol_mocks.rb",
     "test/helpers/scenario_connection.rb",
     "test/io_extensions_test.rb",
     "test/server_test.rb",
     "test/socket_factory_test.rb",
     "test/test_helper.rb",
     "test/tunnel_test.rb"
  ]

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<eventmachine>, [">= 0.12.2"])
      s.add_runtime_dependency(%q<net-ssh>, [">= 2.0.4"])
      s.add_development_dependency(%q<rspec>, [">= 1.3.0"])
      s.add_development_dependency(%q<simple-daemon>, [">= 0.1.2"])
      s.add_development_dependency(%q<thin>, [">= 1.0.0"])
    else
      s.add_dependency(%q<eventmachine>, [">= 0.12.2"])
      s.add_dependency(%q<net-ssh>, [">= 2.0.4"])
      s.add_dependency(%q<rspec>, [">= 1.3.0"])
      s.add_dependency(%q<simple-daemon>, [">= 0.1.2"])
      s.add_dependency(%q<thin>, [">= 1.0.0"])
    end
  else
    s.add_dependency(%q<eventmachine>, [">= 0.12.2"])
    s.add_dependency(%q<net-ssh>, [">= 2.0.4"])
    s.add_dependency(%q<rspec>, [">= 1.3.0"])
    s.add_dependency(%q<simple-daemon>, [">= 0.1.2"])
    s.add_dependency(%q<thin>, [">= 1.0.0"])
  end
end

